name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Restore gradle wrapper
        run: gradle wrapper

      #- name: Run Tests
        #run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble

      - name: Build
        run: ./gradlew build